### ISSUE TITLE
pihole login failing when no login required

### ISSUE THREAD

**Issue by Brent17** [eko/pihole-exporter#1]
pihole is setup with no user/pass.  Starting exporter without a password but exporter appears to be trying to login anyway and getting confused? 

pi@PIHOLE:~ $ pihole_exporter-linux-arm
2019/05/10 11:57:27 ------------------------------------
2019/05/10 11:57:27 -  PI-Hole exporter configuration  -
2019/05/10 11:57:27 ------------------------------------
2019/05/10 11:57:27 PIHoleHostname : 127.0.0.1
2019/05/10 11:57:27 PIHolePassword :
2019/05/10 11:57:27 Port : 9311
2019/05/10 11:57:27 Interval : 10s
2019/05/10 11:57:27 ------------------------------------
2019/05/10 11:57:27 New Prometheus metric registered: domains_blocked
2019/05/10 11:57:27 New Prometheus metric registered: dns_queries_today
2019/05/10 11:57:27 New Prometheus metric registered: ads_blocked_today
2019/05/10 11:57:27 New Prometheus metric registered: ads_percentag_today
2019/05/10 11:57:27 New Prometheus metric registered: unique_domains
2019/05/10 11:57:27 New Prometheus metric registered: queries_forwarded
2019/05/10 11:57:27 New Prometheus metric registered: queries_cached
2019/05/10 11:57:27 New Prometheus metric registered: clients_ever_seen
2019/05/10 11:57:27 New Prometheus metric registered: unique_clients
2019/05/10 11:57:27 New Prometheus metric registered: dns_queries_all_types
2019/05/10 11:57:27 New Prometheus metric registered: reply
2019/05/10 11:57:27 New Prometheus metric registered: top_queries
2019/05/10 11:57:27 New Prometheus metric registered: top_ads
2019/05/10 11:57:27 New Prometheus metric registered: top_sources
2019/05/10 11:57:27 New Prometheus metric registered: forward_destinations
2019/05/10 11:57:27 New Prometheus metric registered: querytypes
2019/05/10 11:57:27 New Prometheus metric registered: status
2019/05/10 11:57:27 Starting HTTP server
2019/05/10 11:57:38 Unable to login to PI-Hole, got a HTTP status code response '200' instead of '302'

**Comment by eko** [comment]
Hi @Brent17,

Thank you for reporting this issue.

I just fixed this issue: of course, my PI-Hole instance is protected by a password but it seems your not ;)

Anyway, this is now fixed and you should download the new `0.0.3` release (https://github.com/eko/pihole-exporter/releases/tag/0.0.3) binary in order to have it corrected.

Build is in progress but the new binaries should appear in around 5-10 minutes here: https://github.com/eko/pihole-exporter/releases/tag/0.0.3

Thank you!
