### ISSUE TITLE
amd64 linux download is 404

### ISSUE THREAD

**Issue by burgerwhore** [eko/pihole-exporter#107]
The Linux link for Architecture amd64 [ Darwin / Linux / Windows ] is going to a 404 and unable to download.
Is that available for download?

**Comment by bwhitehead0** [comment]
it's not listed under releases for current version 0.1.1 - it is available for previous releases.

is there a reason it's not available for the current release? @Galorhallen

**Comment by eko** [comment]
Hi @burgerwhore  @bwhitehead0,

Sorry for the response delay.

I just made a new https://github.com/eko/pihole-exporter/releases/tag/v0.2.0 release and the link is now available, I think the old one has failed.

Thank you for opening this issue!
