### ISSUE TITLE
pihole_exporter binary for amd64 is missing with release v0.1.1

### ISSUE THREAD

**Issue by jobenvil** [eko/pihole-exporter#115]
Here to the [pihole_exporter binaries of v0.1.1](https://github.com/eko/pihole-exporter/releases/tag/v0.1.1)
 
![image](https://user-images.githubusercontent.com/11994245/150697241-f934be8e-286c-46bd-afcc-7d343cf21280.png)

Or is the `darwin-amd64` the new binary for both? I'm confused.

**Comment by eko** [comment]
Hello,

Thank you for reporting this issue, I just released a new v0.2.0 (https://github.com/eko/pihole-exporter/releases/tag/v0.2.0) and this is now available.
