### ISSUE TITLE
promtail config?

### ISSUE THREAD

**Issue by romprod** [eko/pihole-exporter#123]
Is it possible to use this with promtail instead of prometheus?

I've tried so far to use the following config with promtail but I get the error message
`caller=filetargetmanager.go:235 msg="no path for target" labels="{__address__=\"pihole-exporter:9617\", job=\"pihole\"}"`

My promtail config
- job_name: 'pihole'
  pihole:
    static_configs:
      - targets: ['pihole-exporter:9617']

**Comment by Mario-Hofstaetter** [comment]
@romprod Promtail is intended for scraping log files, not HTTP endpoints.

In the config docs https://grafana.com/docs/loki/latest/clients/promtail/configuration/ no way to scrape an HTTP endpoint is mentioned. Promtail has no scrape interval concept and is live tailing targets.

Instead you could for example regularly `curl` the `/probe` endpoint (missing in your config btw), and write the output (the metrics) to a file which is tailed by promtail.
Even better, run curl in a container and use promtails new `docker_sd_configs` to just scrape the container logs.
Maybe you could also directly push the metrics text with curl and http post to [promtails push api](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#loki_push_api), but I have not used that yet

> Promtail also exposes a second endpoint on /promtail/api/v1/raw which expects newline-delimited log lines. This can be used to send NDJSON or plaintext logs.

**Comment by eko** [comment]
Hi, Promtail is for logs, where Prometheus is for metrics.

This exporter is a Prometheus exporter that exports metrics.

I hope this is much clear for you now.

Thank you
