### ISSUE TITLE
Raspberry PI support for Docker

### ISSUE THREAD

**Issue by wesback** [eko/pihole-exporter#13]
The Docker image does not seem to be multi architecture.
Are you planning on providing an ARM compatible Docker image?

**Comment by eko** [comment]
Hi @wesback,

You’re right, we should be able to build a Docker image for this architecture also.

I am off actually but I could have a look at it on next week

**Comment by jostyee** [comment]
You can build by yourself w/ an one-line change, see:

https://github.com/jostyee/pihole-exporter/commit/74b63fc0bf960f83d32ada3f0d89816c57b600e5

**Comment by onedr0p** [comment]
I have forked this project and provided multi-arch container images.

Sauce: https://gitlab.com/onedr0p/pihole-exporter-test-2 (don't mind the name I will change it to pihole-exporter in a week)
Images: https://hub.docker.com/r/onedr0p/pihole-exporter/tags

**Comment by eko** [comment]
Hi, sorry for the delay, ARMv7 is now the default architecture when building the Docker image.

**Comment by onedr0p** [comment]
@eko the request if for you to provide multi arch Container images. Please re-open this issue.

**Comment by onedr0p** [comment]
@eko take a look at how the digests/manifests appear on your image, and on the one I created.

https://hub.docker.com/r/ekofr/pihole-exporter/tags
vs
https://hub.docker.com/r/onedr0p/pihole-exporter/tags

**Comment by HorayNarea** [comment]
Could you please revert https://github.com/eko/pihole-exporter/commit/9d8446b6475e581a7b6b757de5a1534f0b6be8af as long as there is no image with a correct manifest since it breaks existing use-cases? See #25

As a workaround you could use a second branch which only builds arm images and push them to a `arm`-tag

**Comment by onedr0p** [comment]
Closed again? I would really like to see a multi-arch image so I don't need to maintain a fork of this project.

**Comment by eko** [comment]
I just reverted the change because of @HorayNarea comments and GitHub closes the issue again because I mentioned a fix in the commit message.

@onedr0p Why did you not opened a PR on this project?

**Comment by onedr0p** [comment]
@eko I do not know travis CI well enough, or if it even supports building multi-arch images. On Gitlab this was trivial for me.

**Comment by SShah7433** [comment]
Docker images now being created automatically. Did not tag issue since manifests cannot be created. Currently manifests are only supported with experimental docker features enabled on GitHub runners which they currently are not

**Comment by onedr0p** [comment]
Have you considered using Github Actions to build multi-arch images? I do this for an exporter I created.

https://github.com/onedr0p/radarr-exporter/blob/master/.github/workflows/main.yml

**Comment by JonAnder83** [comment]
I'm trying to use this on my raspberry pi and still don't see support for arm :(
Is there any chance you would add it at some point? Thanks!

**Comment by eko** [comment]
Hi @JonAnder83,

I now have the following Docker images that support both 32 and 64bits arm architectures:
* ekofr/pihole-exporter:arm32
* ekofr/pihole-exporter:arm64

**Comment by eko** [comment]
I just switched to GitHub Actions instead of Travis-CI and also docker buildx (experimental) so now tagged images are available for the following architectures:

<img width="1196" alt="Capture d’écran 2020-05-05 à 14 17 58" src="https://user-images.githubusercontent.com/103900/81065210-54ce2700-8edb-11ea-8d4a-deb43884329d.png">

I think this issue can be closed now :)

**Comment by JonAnder83** [comment]
> 
> 
> Hi @JonAnder83,
> 
> I now have the following Docker images that support both 32 and 64bits arm architectures:
> 
>     * ekofr/pihole-exporter:arm32
> 
>     * ekofr/pihole-exporter:arm64

Hi!
On a raspberry pi 3, I tried:
ekofr/pihole-exporter:arm32
and
ekofr/pihole-exporter:arm

And both got me the message:

standard_init_linux.go:211: exec user process caused "exec format error"

Which usually means wrong architecture. :(

**Comment by eko** [comment]
@JonAnder83 Could you try the `ekofr/pihole-exporter:0.0.9` image please? This is the latest multi-architecture image available here: https://hub.docker.com/layers/ekofr/pihole-exporter/0.0.9/images/sha256-9c32c4b09a3d271501896bcd938f0a54bb6e4c9bd6b44e42e77c44814ac3ea8d?context=repo

**Comment by JonAnder83** [comment]
> 
> 
> @JonAnder83 Could you try the `ekofr/pihole-exporter:0.0.9` image please? This is the latest multi-architecture image available here: https://hub.docker.com/layers/ekofr/pihole-exporter/0.0.9/images/sha256-9c32c4b09a3d271501896bcd938f0a54bb6e4c9bd6b44e42e77c44814ac3ea8d?context=repo

Yes!! That one did the trick!
Please, feel free to count on me if you want to test for arm deployments in the future :)

**Comment by eko** [comment]
@JonAnder83 Great, the next images will use these types of multi-architecture too :)

Cool to hear that it's working for you now, and thank you for your proposition to test future releases on arm!

Closing this issue now

**Comment by eko** [comment]
Hi @rbosneag,

Thank you, I just removed the tags `arm` & `arm64` and the GitHub Action that was building them: they should not be used anymore.

I now provide a multi-architecture docker image and the latest version you can use is `ekofr/pihole-exporter:v0.0.11`.

Thank you
