### ISSUE TITLE
pihole-exporter kill himself because of pihole unreachable

### ISSUE THREAD

**Issue by bilyboy785** [eko/pihole-exporter#158]
**Steps for Reproduction**

1. All is running good
2. One or more PiHole instance is down
3. pihole-exporter docker stop because of timeout ? 

**Expected behavior**:
Could it be possible to not kill the pihole-exporter ? I shutdown my pihole each night between 00:00 and 07:00. 

**Actual behavior**:

**Platforms**:
pihole-exporter on Docker, Ubuntu 20.04

**Versions**:
Latest image docker

**Comment by 0xEmma** [comment]
Having a similar issue where it'll timeout, and crash. Since its in the same kubernetes deployment as pihole itll take down the service until exporter is working again, a graceful fail would be very much appreciated
