### ISSUE TITLE
Available Grafana Dasboards does not exists

### ISSUE THREAD

**Issue by AlekseyLobanov** [eko/pihole-exporter#160]
404 for selected links
![image](https://user-images.githubusercontent.com/3019536/211305469-b1cfd3bb-a35b-4818-aa36-968b716a3fb2.png)

**Comment by mentalsoup** [comment]
https://grafana.com/grafana/dashboards/10176-pi-hole-exporter/

**Comment by AlekseyLobanov** [comment]
Selected links are different: 
- https://grafana.com/dashboards/10176
- https://grafana.com/dashboards/17094

Maybe they should be updated.
