### ISSUE TITLE
pie chart not found

### ISSUE THREAD

**Issue by voxie12** [eko/pihole-exporter#164]
![image](https://user-images.githubusercontent.com/65469239/220131773-9b424da3-a28b-4d8e-af5a-32b8464b39c1.png)

the panels are missing.

**Platforms**:
i use firefox version 110

my rpi4:
```
       _,met$$$$$gg.          jay@raspberrypi
    ,g$$$$$$$$$$$$$$$P.       ---------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) aarch64
 ,$$P'              `$$$.     Host: Raspberry Pi 4 Model B Rev 1.1
',$$P       ,ggs.     `$$b:   Kernel: 5.15.84-v8+
`d$$'     ,$P"'   .    $$$    Uptime: 12 hours, 51 mins
 $$P      d$'     ,    $$P    Packages: 706 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/0
 Y$$.    `.`"Y$$$$P"'         CPU: BCM2835 (4) @ 1.500GHz
 `$$b      "-.__              Memory: 375MiB / 3794MiB
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
```

**Versions**:
pihole-exporter 0.3.0

**Comment by Krafting** [comment]
Same here, on Grafana 8.1.0. 

Graphana deprecated the plugin grafana-piechart-panel as it is now baked inside grafana .

**Comment by s0nify** [comment]
Hello!

It is enough to change the type to a new pie-chart and it will work. 
Click on panel, edit, you will see: Panel plugin not found (grafana-piechart-panel), just change it to the new pie-chart plugin.
