### ISSUE TITLE
Problem Getting Grafana Dashboard To See Prometheus Data

### ISSUE THREAD

**Issue by GregHilston** [eko/pihole-exporter#2]
When I copy your Grafana dashboard, id `10176`, the dashboard is empty. Any advice for someone new to this tool?

**Comment by eko** [comment]
Hi @GregHilston,

Have you also tried to download the JSON file from the following link: https://grafana.com/api/dashboards/10176/revisions/2/download ?

Then, you can upload it manually into your Grafana instance.

Does not hesitate to reply if you still have an issue, elsewhere could you close this issue please?

Thank you for your feedback!

**Comment by GregHilston** [comment]
Hey @eko,

I also did try out loading in the JSON. I started reading through it and I _think_ I might know what's causing it. Is it fair to say that this dashboard looks at `localhost` for the prometheus install?

I saw a few mentions of `localhost` and tried to replace that with the local IP address of where my prometheus install is running (a docker container, just like grafana, on the same docker network).

**Comment by GregHilston** [comment]
I had to edit the JSON to point to the correct data source and all worked well, thank you!

**Comment by eko** [comment]
Great to know that you've successfully set it up. I will try to have a look at it in the coming days.

Thank you

**Comment by GregHilston** [comment]
I'll make a new issue
