### ISSUE TITLE
Support for multiply PI Hole Servers central Prometheus

### ISSUE THREAD

**Issue by RedJohn14** [eko/pihole-exporter#23]
Hello,

any idea for Support for multiply PI Hole Servers? One central Prometheus Servers? And exporter are running on each PI Hole? Or one central Prometheus Server and one or two exporters on the Prometheus?

Did I need two exporters or can I use one exporter for two PI Holes?

**Comment by dannyk81** [comment]
The general approach with Prometheus is to run an exporter per monitored instance, so each pihole instance should have a "sidecar" exporter.

**Comment by eko** [comment]
Yep, this is the best practice.

Thank you for your answers

**Comment by AlfaJackal** [comment]
I have to pihole exporter instances. Unfortunately both of them show the same hostname in influx. How do I fix that?

First Docker Instance:
`PIHOLE_HOSTNAME: 10.0.0.13`
`PIHOLE_PORT: 9617`

Second Instance:
`PIHOLE_HOSTNAME: 10.0.0.3`
`PIHOLE_PORT: 9617`

Scrape Job:
```
- job_name: 'pihole'
static_configs:
- targets: ['10.10.0.6:9617']
- job_name: 'pihole2'
static_configs:
- targets: ['10.10.0.6:9617']
```

If I change the port to 9617, Prometheus cannot connect.

Any ideas?

**Comment by AlfaJackal** [comment]
Sorry for being too fast! Changing the local port in docker did it! 😊

**Comment by eko** [comment]
Great to see it’s finally working ;)
Have fun!
