### ISSUE TITLE
Problem adding pihole-exporter as a Prometheus datasource in Grafana

### ISSUE THREAD

**Issue by weirdvic** [eko/pihole-exporter#241]
Hello,

I encountered an issue while trying to add pihole-exporter as a Prometheus datasource in the current Grafana version (11.2.0).

The problem is that when Grafana adds a Prometheus datasource, it queries the `/api/v1/status/buildinfo` URL. Since pihole-exporter does not provide this path, the addition of the datasource fails.

A possible solution would be to implement a minimal version of the [Build Information API](https://prometheus.io/docs/prometheus/latest/querying/api/#build-information), probably using Go's `runtime/debug` package.

**Comment by solipsist01** [comment]
you add 'prometheus' as a datasource to grafana
pihole has nothing to do with that :)

pihole has a namespace, within prometheus, yes., but you don't add that, you query that, when havving added prometheus as a datasource.

**Comment by weirdvic** [comment]
> you add 'prometheus' as a datasource to grafana pihole has nothing to do with that :)
> 
> pihole has a namespace, within prometheus, yes., but you don't add that, you query that, when havving added prometheus as a datasource.

I guess I got it now. It is not possible to use pihole-exporter as a source in Grafana. The pihole-exporter just provides metrics to be collected by a Prometheus instance which could be used as a datasource in Grafana, something like that:
``` mermaid
flowchart TD;
pihole-exporter --> Prometheus --> Grafana
```

Sorry for the distraction then, the problem is solved!
