### ISSUE TITLE
Crashing/unable to start on docker v0.0.7

### ISSUE THREAD

**Issue by stephanrenggli** [eko/pihole-exporter#25]
After updating from 0.0.6 to 0.0.7 (docker container) the application does no longer start.

Configuration is done via environment variables which have not been changed between the two versions. The following variables are set:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PASSWORD="password"
      - INTERVAL=30s
      - PORT=9617

**Steps for Reproduction**

1. Update from 0.0.6 to 0.0.7
2. Start container
3. Error appears

**Expected behavior**:
Application starts successfully

**Actual behavior**:
Application does not start or crashes on start with the following error message:
`standard_init_linux.go:211: exec user process caused "exec format error" pihole exporter`

**Platforms**:
Docker on Ubuntu

**Versions**:
Docker version 19.03.5, build 633a0ea838
pihole-exporter version 0.0.7

**Comment by PhantomGhost** [comment]
I was just trying to set this up for the first time, using the latest docker image, and I get the same error on start.

**Comment by eko** [comment]
Hi,

Thank you for your feedback, this is fixed as I reverted the change in new `0.0.8` tag.

This was due to a wrong GOARCH argument in Dockerfile
