### ISSUE TITLE
Unable to unmarshal PI-Hole statistics to statistics struct model invalid character 'F' looking for beginning of value

### ISSUE THREAD

**Issue by kquinsland** [eko/pihole-exporter#26]
**First**: Thank you for building this tool! I am grateful that it exists and is free!

------

**Steps for Reproduction**

I am running piHole behind a proxy. This allows me to redirect http requests to HTTPS.
I am getting the error seen above when I try to run the exporter.

Here's a fuller output:

```
# systemctl start phole-metrics; journalctl -xfe -u pihole-metrics
    <SNIP> 
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 ------------------------------------
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 -  PI-Hole exporter configuration  -
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 ------------------------------------
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 PIHoleHostname : 127.0.0.1
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 PIHolePassword : my-pihole-password
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 Port : 9617
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 Interval : 10s
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 ------------------------------------
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: domains_blocked
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: dns_queries_today
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: ads_blocked_today
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: ads_percentag_today
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: unique_domains
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: queries_forwarded
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: queries_cached
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: clients_ever_seen
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: unique_clients
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: dns_queries_all_types
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: reply
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: top_queries
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: top_ads
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: top_sources
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: forward_destinations
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: querytypes
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 New Prometheus metric registered: status
Feb 08 18:42:01 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:01 Starting HTTP server
Feb 08 18:42:11 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:11 Unable to unmarshal PI-Hole statistics to statistics struct model invalid character 'F' looking for beginning of value
Feb 08 18:42:11 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:11 New tick of statistics: 0 ads blocked / 0 total DNS queries
Feb 08 18:42:21 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:21 Unable to unmarshal PI-Hole statistics to statistics struct model invalid character 'F' looking for beginning of value
Feb 08 18:42:21 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:21 New tick of statistics: 0 ads blocked / 0 total DNS queries
Feb 08 18:42:31 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:31 Unable to unmarshal PI-Hole statistics to statistics struct model invalid character 'F' looking for beginning of value
Feb 08 18:42:31 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:31 New tick of statistics: 0 ads blocked / 0 total DNS queries
Feb 08 18:42:41 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:41 Unable to unmarshal PI-Hole statistics to statistics struct model invalid character 'F' looking for beginning of value
Feb 08 18:42:41 myHost pihole-metrics-exporter[8897]: 2020/02/08 18:42:41 New tick of statistics: 0 ads blocked / 0 total DNS queries
^C

```

I am not a golang person, but i was able to poke about and found the URL you hit for stats scraping. I don't know how to force a more verbose log from the `err = json.Unmarshal(body, &stats)` call.

In any event here's what I was able to pull from my piHole through the proxy using `curl`:

1. Log in; submit the PW and store the cookie in the `cookie-jar` so i can re-use the cookies when i request the stats. I have told `cURL` to ignore TLS certificate issues (`--insecure`) and follow any redirects (`-L`):

```
root@myHost:/# curl 'https://my.host.ip.v4/admin/index.php?login' --cookie-jar ./cookies --insecure -L -H 'Origin: https://my.host.ip.v4' -H 'Referer: https://my.host.ip.v4/admin/index.php?login' -H 'Cookie: PHPSESSID=m2ei7n7d49h7t04is85gp1325j' -H 'TE: Trailers' --data 'pw=my-pihole-password'
<!DOCTYPE html>
<!-- Pi-hole: A black hole for Internet advertisements
*  (c) 2017 Pi-hole, LLC (https://pi-hole.net)
*  Network-wide ad blocking via your own hardware.
*
*  This file is copyright under the latest version of the EUPL.
*  Please see LICENSE file for your rights under this license. -->
<html>
<head>
   <SNIP>
</body>
</html>
```

Now, request the stats:

```
root@myHost:/# curl 'http://my.host.ip.v4/admin/api.php?summaryRaw&overTimeData&topItems&recentItems&getQueryTypes&getForwardDestinations&getQuerySources&jsonForceObject' --cookie-jar ./cookies --insecure -L

{"domains_being_blocked":1,"dns_queries_today":1817,"ads_blocked_today":0,"ads_percentage_today":0,"unique_domains":17,"queries_forwarded":240,"queries_cached":1577,"clients_ever_seen":1,"unique_clients":1,"dns_queries_all_types":1817,"reply_NODATA":34,"reply_NXDOMAIN":1,"reply_CNAME":112,"reply_IP":1577,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1581212031,"relative":{"days":"0","hours":"01","minutes":"15"}}}
```

That looks like valid JSON to me, so i'm going to assume that something _else_ is in `body` when it's passed onto `json.Unpashal`.

Again: not a golang person... but this would look like either `ReadAll` is objecting to TLS certificate error or is not following redirects. Can't be certain as `body` is never dumped to console :/.

**Versions**:

Which versions are you running?

_side note_ *strongly* consider adding a git hash into the built binary. See [here](https://preslav.me/2019/07/09/adding-version-information-to-go-binaries/) for a golang related technique. 

This way, the startup preamble text that gets logged would clue you into the version :).

Anyways, i am using version `0.0.8` the linux/64 version:
I am not using docker. I am using systemd
```
root@myHost:/# shasum $(which pihole-metrics-exporter)
efe4169bc237861378aac6c7a497cfbdd41bc3c7  /usr/bin/pihole-metrics-exporter
root@myHost:/# pihole-metrics-exporter --version
flag provided but not defined: -version
Usage of pihole-metrics-exporter:
  -interval duration
    	 (default 10s)
  -pihole_hostname string
    	 (default "127.0.0.1")
  -pihole_password string

  -port string
    	 (default "9617")
```

Let me know if there's anything else i can do to help.

**Comment by kquinsland** [comment]
Did a bit of testing and was able to confirm that things are _fine_ when circumventing the proxy.

**Note**: Port `9090` is the native port that piHole listens on / the port my TLS terminating proxy forwards traffic to.

from `jourrnalctl`:

```
    <SNIP>
2020/02/09 07:53:44 ------------------------------------
2020/02/09 07:53:44 -  PI-Hole exporter configuration  -
2020/02/09 07:53:44 ------------------------------------
2020/02/09 07:53:44 PIHoleHostname : 127.0.0.1:9090
2020/02/09 07:53:44 PIHolePassword : my-pihole-password
2020/02/09 07:53:44 Port : 9617
2020/02/09 07:53:44 Interval : 10s
2020/02/09 07:53:44 ------------------------------------
2020/02/09 07:53:44 New Prometheus metric registered: domains_blocked
    <SNIP>
2020/02/09 07:53:44 New Prometheus metric registered: status
2020/02/09 07:53:44 Starting HTTP server
2020/02/09 07:53:54 New tick of statistics: 0 ads blocked / 11759 total DNS queries

```

**Comment by geoff-coppertop** [comment]
I see the same issue when using a FQDN served by Traefik. I'm guessing that the exporter is appending /admin<rest of path to API> which isn't necessary in my setup but would be necessary when using a raw IP.

**Comment by jobenvil** [comment]
> I see the same issue when using a FQDN served by Traefik. I'm guessing that the exporter is appending /admin which isn't necessary in my setup but would be necessary when using a raw IP.

@kquinsland @geoff-coppertop Having same issue with one of my pi-hole which is being served by `nginx`, FQDN + `https` (not by the default `lighttpd` server)!

I got it running, changing `admin` by your `nginx` pattern, in my case `agujero` in `internal/pihole/client.go`

 ```
18         loginURLPattern = "https://%s/agujero/index.php?login"
 19         statsURLPattern = "https://%s/agujero/api.php?summaryRaw&overTimeData&topItems&recentItems&getQueryTypes&getForwardDestinations&getQuerySources&jsonForceObject"
```
`http `to `https` as well, if not you will still get the same issue.

and then compile the src of `pihole_exporter`

```
# go get -u github.com/eko/pihole-exporter
# cd ~/go/src/github.com/eko/pihole-exporter
# env GOOS=linux GO111MODULE=on GOARCH=arm GOARM=7 sudo go build -o pihole_exporter .
```
Run the `pihole_exporter` binary:

```
./pihole_exporter -pihole_api_token 1ajksahfdksdhfklsadhflaksjetc,etc,etc,andale,andale -pihole_hostname freeassange.de
```
**Instead of the IP of the host, substitute by the FQDN Domain.**

In my case `nginx `is like here:

    location /agujero {

     #  auth_basic              "Not currently available";   WATCH OUT NOW IS OFF
     #   auth_basic_user_file    /etc/nginx/.htpasswd;  WATCH OUT NOW IS OFF

        root /var/www/html;
        index index.php;

        error_log       /var/log/nginx/pihole_hiperborea_error.log;
        access_log      /var/log/nginx/pihole_hiperborea_acces.log; #off;

        location ~ \.php$ {
            fastcgi_index       /admin/index.php;
            include             /etc/nginx/fastcgi.conf;
            fastcgi_pass        unix:/var/run/php/php7.4-fpm.sock;
            fastcgi_param       FQDN true;

            fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;

            # estas tres lineas mitigan el fallo CORS: Failed CORS: null vs 192...., , freeassange.de, pi.hole, localhost
            add_header          'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
            proxy_set_header    host $host;
            proxy_set_header    X-real-ip $remote_addr;
            proxy_set_header    X-forward-for $proxy_add_x_forwarded_for;

            error_log       /var/log/nginx/pihole_hiperborea_php_error.log;
            access_log      /var/log/nginx/pihole_hiperborea_php_acces.log; #off;
        }
     }
Watch that I had to switch off the basic authorization on `nginx` in order to be able to pull the metrics.

Here the logs:
```

2020/06/01 23:04:27 ------------------------------------
2020/06/01 23:04:27 -  PI-Hole exporter configuration  -
2020/06/01 23:04:27 ------------------------------------
2020/06/01 23:04:27 PIHoleHostname : freeassange.de
2020/06/01 23:04:27 Pi-Hole Authentication Method : PIHoleApiToken
2020/06/01 23:04:27 Port : 9617
2020/06/01 23:04:27 Interval : 10s
2020/06/01 23:04:27 ------------------------------------
2020/06/01 23:04:27 New Prometheus metric registered: domains_blocked
2020/06/01 23:04:27 New Prometheus metric registered: dns_queries_today
2020/06/01 23:04:27 New Prometheus metric registered: ads_blocked_today
2020/06/01 23:04:27 New Prometheus metric registered: ads_percentag_today
2020/06/01 23:04:27 New Prometheus metric registered: unique_domains
2020/06/01 23:04:27 New Prometheus metric registered: queries_forwarded
2020/06/01 23:04:27 New Prometheus metric registered: queries_cached
2020/06/01 23:04:27 New Prometheus metric registered: clients_ever_seen
2020/06/01 23:04:27 New Prometheus metric registered: unique_clients
2020/06/01 23:04:27 New Prometheus metric registered: dns_queries_all_types
2020/06/01 23:04:27 New Prometheus metric registered: reply
2020/06/01 23:04:27 New Prometheus metric registered: top_queries
2020/06/01 23:04:27 New Prometheus metric registered: top_ads
2020/06/01 23:04:27 New Prometheus metric registered: top_sources
2020/06/01 23:04:27 New Prometheus metric registered: forward_destinations
2020/06/01 23:04:27 New Prometheus metric registered: querytypes
2020/06/01 23:04:27 New Prometheus metric registered: status
2020/06/01 23:04:27 Starting HTTP server
2020/06/01 23:04:38 New tick of statistics: 4 ads blocked / 9396 total DNS queries
2020/06/01 23:04:47 New tick of statistics: 4 ads blocked / 9396 total DNS queries
2020/06/01 23:04:57 New tick of statistics: 4 ads blocked / 9396 total DNS queries

```

**Comment by eko** [comment]
Thanks you all for your help on this issue. Closing for now, feel free to reopen if you still have an issue.

**Comment by techie2000** [comment]
@eko I was previously running the 0.0.11 docker when I observed this issue. I have just switched to :latest tag and still get the same error
```
2021/03/23 10:14:42 - PI-Hole exporter configuration -
2021/03/23 10:14:42 ------------------------------------
2021/03/23 10:14:42 PIHoleProtocol : http
2021/03/23 10:14:42 PIHoleHostname : 192.168.1.115
2021/03/23 10:14:42 PIHolePort : 80
2021/03/23 10:14:42 Pi-Hole Authentication Method : PIHolePassword
2021/03/23 10:14:42 Port : 9617
2021/03/23 10:14:42 Interval : 30s
2021/03/23 10:14:42 ------------------------------------
2021/03/23 10:14:42 New Prometheus metric registered: domains_blocked
2021/03/23 10:14:42 New Prometheus metric registered: dns_queries_today
2021/03/23 10:14:42 New Prometheus metric registered: ads_blocked_today
2021/03/23 10:14:42 New Prometheus metric registered: ads_percentag_today
2021/03/23 10:14:42 New Prometheus metric registered: unique_domains
2021/03/23 10:14:42 New Prometheus metric registered: queries_forwarded
2021/03/23 10:14:42 New Prometheus metric registered: queries_cached
2021/03/23 10:14:42 New Prometheus metric registered: clients_ever_seen
2021/03/23 10:14:42 New Prometheus metric registered: unique_clients
2021/03/23 10:14:42 New Prometheus metric registered: dns_queries_all_types
2021/03/23 10:14:42 New Prometheus metric registered: reply
2021/03/23 10:14:42 New Prometheus metric registered: top_queries
2021/03/23 10:14:42 New Prometheus metric registered: top_ads
2021/03/23 10:14:42 New Prometheus metric registered: top_sources
2021/03/23 10:14:42 New Prometheus metric registered: forward_destinations
2021/03/23 10:14:42 New Prometheus metric registered: querytypes
2021/03/23 10:14:42 New Prometheus metric registered: status
2021/03/23 10:14:42 Starting HTTP server
2021/03/23 10:15:12 Unable to unmarshal PI-Hole statistics to statistics struct model invalid character '<' looking for beginning of value
2021/03/23 10:15:12 New tick of statistics: 0 ads blocked / 0 total DNS queries
```

**Comment by feloxxx** [comment]
First of all, thank you very much for the effort and the preparation of this great tool.

I'm using Debian 11 and the current version of Pihole 5.17.3 with the built-in web server. The installation of Pihole works perfectly for me.
When I start the exporter with the following command:
pihole_exporter -pihole_hostname 192.168.111.3 -pihole_port=9617 -pihole_api_token=693259d26f25dd1c0badf32090c08b5b8d7a0bafaf9c1b9181978913756c2340

I receive the following messages:

INFO[0000] ------------------------------------
INFO[0000] -  PI-Hole exporter configuration  -
INFO[0000] ------------------------------------
INFO[0000] PIHoleProtocol : [http]
INFO[0000] PIHoleHostname : [192.168.111.3]
INFO[0000] PIHolePort : [9617]
INFO[0000] Pi-Hole Authentication Method : PIHoleApiToken
INFO[0000] Port : 9617
INFO[0000] Timeout : 5s
INFO[0000] ------------------------------------
INFO[0000] New Prometheus metric registered: domains_blocked
INFO[0000] New Prometheus metric registered: dns_queries_today
INFO[0000] New Prometheus metric registered: ads_blocked_today
INFO[0000] New Prometheus metric registered: ads_percentag_today
INFO[0000] New Prometheus metric registered: unique_domains
INFO[0000] New Prometheus metric registered: queries_forwarded
INFO[0000] New Prometheus metric registered: queries_cached
INFO[0000] New Prometheus metric registered: clients_ever_seen
INFO[0000] New Prometheus metric registered: unique_clients
INFO[0000] New Prometheus metric registered: dns_queries_all_types
INFO[0000] New Prometheus metric registered: reply
INFO[0000] New Prometheus metric registered: top_queries
INFO[0000] New Prometheus metric registered: top_ads
INFO[0000] New Prometheus metric registered: top_sources
INFO[0000] New Prometheus metric registered: forward_destinations
INFO[0000] New Prometheus metric registered: querytypes
INFO[0000] New Prometheus metric registered: status
INFO[0000] Creating client with config <Config@C000210050 PIHoleProtocol=http, PIHoleHostname=192.168.111.3, PIHolePort=9617, PIHoleApiToken=*****>
INFO[0000] Starting HTTP server
INFO[0012] request.Header: map[Accept:[application/openmetrics-text;version=1.0.0;q=0.5,application/openmetrics-text;version=0.0.1;q=0.4,text/plain;version=0.0.4;q=0.3,*/*;q=0.2] Accept-Encoding:[gzip] User-Agent:[Prometheus/2.51.0] X-Prometheus-Scrape-Timeout-Seconds:[10]]
INFO[0012] Collecting from 192.168.111.3
INFO[0012] An error occured while contacting 192.168.111.3: unable to unmarshal PI-Hole statistics to statistics struct model: invalid character 'p' after top-level value
INFO[0027] request.Header: map[Accept:[application/openmetrics-text;version=1.0.0;q=0.5,application/openmetrics-text;version=0.0.1;q=0.4,text/plain;version=0.0.4;q=0.3,*/*;q=0.2] Accept-Encoding:[gzip] User-Agent:[Prometheus/2.51.0] X-Prometheus-Scrape-Timeout-Seconds:[10]]
INFO[0027] Collecting from 192.168.111.3
INFO[0027] An error occured while contacting 192.168.111.3: unable to unmarshal PI-Hole statistics to statistics struct model: invalid character 'p' after top-level value
^C2024/03/25 08:41:01 pihole-exporter HTTP server stopped


I can't find the error and I don't use a docker installation. Does anyone have an idea? Thank you so much!
