### ISSUE TITLE
Where is prometheus.yml?

### ISSUE THREAD

**Issue by RobertJClegg** [eko/pihole-exporter#34]
I downloaded the binary and then ran: 

`./pihole_exporter-linux-amd64 -pihole_hostname 192.168.1.202 -pihole_password passs!`

Which then works and reports: 
`2020/03/22 13:12:32 New tick of statistics: 3249 ads blocked / 32319 total DNS queries`
Every 10s. 

However in the read me we are told then to update ` prometheus.yml` - I have searched my server for this file and just don't see it anywhere. Please could you tell me where it is? \\\

I'll then do a new PR to update the readme as it really isn't clear how we add the job. 

Thanks for the great work!

**Comment by eko** [comment]
Hi,

`prometheus.yml` is the configuration file of Prometheus server. You need to have a Prometheus server because it's the database containing your PI Hole data.

See https://prometheus.io/docs/prometheus/latest/installation/ for more details concerning installation.

Thank you
