### ISSUE TITLE
Docker environment var documentation

### ISSUE THREAD

**Issue by proggaras** [eko/pihole-exporter#4]
Would it be possible to add the possible password environment vars to the documentation? 
-e PIHOLE_PASSWORD=xxxxxx 
Guess It would help many people to save time.

**Comment by eko** [comment]
Thank you @proggaras,

I've just added all environment variables on the README file:

```
$ docker run \
  -e 'PIHOLE_HOSTNAME=192.168.1.2' \
  -e 'PIHOLE_PASSWORD=mypassword' \
  -e 'INTERVAL=30s' \
  -e 'PORT=93111' \
  ekofr/pihole-exporter:latest
```
