### ISSUE TITLE
Ones should be able to set the pi-hole UI port

### ISSUE THREAD

**Issue by gnuowned** [eko/pihole-exporter#41]
I have one of my PI-holes on a different port, no the 80 but 8080, one should be able to set the pi-hole UI port. 

thank you for the exporter BTW :-D

**Comment by shaned24** [comment]
You can see the port after the host name, see below

```
export PIHOLE_HOSTNAME={host}:{port}

# ie

export PIHOLE_HOSTNAME=127.0.0.1:8080
```

**Comment by eko** [comment]
Indeed, the port can be set this way.

Thank you for your feedbacks, closing this issue now but feel free to reopen if you still have any issue concerning the port.
