### ISSUE TITLE
OLD DATA FROM PIHOLE STILL DISPLAYS AFTER FLUSHING PIHOLE

### ISSUE THREAD

**Issue by neil1962** [eko/pihole-exporter#50]
Using a Prometheus DB and using your PI Hole stats graph.  When the data is flushed flush from PI Hole via the web gui your graphs are still reporting data (old) that no longer exists in Pi Hole. Is there some setting I am maybe missing in Prometheus? The PI hole top sources is one for example.  I have tried setting the data time on the graph to 5 minutes to ensure it is picking up only the last 5 minutes of data after the PI hole flush. The one I mentioned above as an example still shows old data.  Some lag or something in updating data in the Prometheus DB maybe?...

In addition has there been any changes with new PI hole version 5 to use the new local DNS records?

**Comment by bwees** [comment]
Prometheus acts as a database so if you want to flush that data, you must clear the Prometheus directory where it is storing data. This is how Grafana is able to get previous data points from Prometheus even before the graphics created or metric is accessed

**Comment by eko** [comment]
Hi,

Indeed, Prometheus stores its metrics on disk, please take a look at this: https://prometheus.io/docs/prometheus/latest/storage/

Closing this issue
