### ISSUE TITLE
Metrics missing when run as system

### ISSUE THREAD

**Issue by somedudebob** [eko/pihole-exporter#51]
Hi

Running on pi, Co hosted with pihole,

When running as system, some metrics are not being recieved, but when ran on commandline with ./pihole_exporter-linux-arm -pihole_password PASSWORD all metrics come through ok

I think its because when ran as system the -pihole_password tag isnt being passed from reading through a few closed tickets, However I am not sure where/how that should be done?

Thanks for any help in advance!

**Comment by eko** [comment]
Hi,

Please use:

```bash
$ ./pihole_exporter-linux-arm -pihole_password=PASSWORD
```

Or use PiHole's web password as an API token instead of the password :

```bash
$ API_TOKEN=$(awk -F= -v key="WEBPASSWORD" '$1==key {print $2}' /etc/pihole/setupVars.conf)
$ ./pihole_exporter-linux-arm -e "PIHOLE_API_TOKEN=$API_TOKEN"
```

Closing this issue for now, please feel free to reopen if you still have an issue.
