### ISSUE TITLE
arm64 docker images don't appear to work on raspberry pi 4

### ISSUE THREAD

**Issue by Ruddickmg** [eko/pihole-exporter#60]
**Steps for Reproduction**

1. deploy ekofr/pihole-exporter:arm64 to kubernetes (on raspberry pi 4)

**Expected behavior**:

pihole-exporter runs without error

**Actual behavior**:

pihole crashes with: standard_init_linux.go:211: exec user process caused "exec format error" 
(typical error when trying to run non arm images on arm arch)

**Platforms**:

raspberry pi 4
Ubuntu 20.04.1 LTS 64-bit
k3s

**Versions**:
arm64 docker image

**Comment by Ruddickmg** [comment]
ekofr/pihole-exporter:0.0.9 works fine as mentioned [here ](https://github.com/eko/pihole-exporter/issues/57)

**Comment by eko** [comment]
Yep, please use the tagged version which supports multi-architecture.

Thank you, closing this issue
