### ISSUE TITLE
Permission Denied error running AMD64 binary

### ISSUE THREAD

**Issue by HL52840** [eko/pihole-exporter#63]
When running the AMD64 binary, `bash` errors out with a Permission Denied error, even when using root privileges. 

**Steps for Reproduction**

1. Download binary using `wget https://github.com/eko/pihole-exporter/releases/latest/download/pihole_exporter-linux-amd64`
2. Launch binary with `./pihole_exporter-linux-amd64` with root
3. Observe error

**Expected behavior**: Get an error from application.

**Actual behavior**: Get an error from `bash` saying that permission is denied, even when using root.

**Platforms**:

Debian 10, Pi-hole 5.1.2

**Versions**:

Pi-hole 5.1.2, Binary version 0.0.10, downloaded as of 10/29/2020.

**Comment by HL52840** [comment]
![image](https://user-images.githubusercontent.com/65380846/97651595-c06ff780-1a19-11eb-80b6-62e98197e071.png)
 SSH access was used, if that matters.

**Comment by theckman** [comment]
@HL52840 do you need the `arm` build instead of `amd64`?

**Comment by HL52840** [comment]
I am running Pi-hole on AMD64. Hyper-V VM if that matters.

**Comment by jobenvil** [comment]
@HL52840 after you downloaded `pihole_exporter-*` with `wget `you should provide executation rights to the binary file:

```
jobenvil@apollo:/opt/pihole-exporter$ ./pihole_exporter-linux-amd64
-bash: ./pihole_exporter-linux-amd64: Permission denied
jobenvil@apollo:/opt/pihole-exporter$ chmod u+x pihole_exporter-linux-amd64
jobenvil@apollo:/opt/pihole-exporter$ ./pihole_exporter-linux-amd64
2021/01/07 21:51:55 ------------------------------------
2021/01/07 21:51:55 -  PI-Hole exporter configuration  -
2021/01/07 21:51:55 ------------------------------------
2021/01/07 21:51:55 PIHoleProtocol : http
2021/01/07 21:51:55 PIHoleHostname : 127.0.0.1
2021/01/07 21:51:55 PIHolePort : 80
2021/01/07 21:51:55 Port : 9617
2021/01/07 21:51:55 Interval : 10s
```

By default, no execution rights are given to dwnloaded files. Change mode is your best friend here:

`$ chmod u+x pihole_exporter-linux-amd64`

Please doble check and if proceed, close the issue for the sake of good habits and, in turn, making happy the maintainer @eko

**Comment by HL52840** [comment]
Worked. Thanks for your help!
