### ISSUE TITLE
Sawtooth Pattern on dns query counts

### ISSUE THREAD

**Issue by bwees** [eko/pihole-exporter#64]
I am trying to verify the behavior of this exporter for both ```pihole_ads_blocked_today``` and ```pihole_dns_queries_all_types``` where I am seeing a sawtooth pattern that drops 2-5k every hour.

**Steps for Reproduction**

Use version 0.0.10 (latest at the current time) on docker hub for arm v7.

**Expected behavior**:
A steady increase in total ads blocked today 

**Actual behavior**:
I have a graph in grafana for pihole_ads_blocked_today. I get a sawtooth pattern that drops about 500 every hour. This results in a sawtooth pattern.

**Platforms**:

ARMv7 (Raspberry Pi 3B+)

**Versions**:
0.0.10 of exporter
5.0 of pi-hole

![image](https://user-images.githubusercontent.com/12686250/98173173-a1151680-1ec0-11eb-8375-0847c17fac77.png)

**Comment by kquinsland** [comment]
I haven't looked too closely,  but i _think_ this is because pihole uses a 'last 24h' window and so every hour the data from what is now 25 hours ago is removed from the rolling window.

**Comment by bwees** [comment]
Ok thank you for the clarification!

Brandon Wees

**Comment by eko** [comment]
Hi, exactly, this is the mechanism of PI-Hole, not a bug due to the exporter.
Maybe using PromQL you can do something to avoid this sawtooth pattern.
