### ISSUE TITLE
PIHolePort Variable Not working

### ISSUE THREAD

**Issue by DasCondor** [eko/pihole-exporter#69]
So I am not sure if you have this parameter enabled or not, but from looks you only it to default to port 80. 

**Steps for Reproduction**
Docker Config
So I read through the Readme and the some of the code, I found an option for (example) 'PIHolePort=8800'.

Same with both PIHOLE_PASSWORD as well. 
As well as without the PIHolePort Parameter.
docker run \
  -e 'PIHOLE_HOSTNAME=192.168.1.200' \
  -e 'PIHOLE_API_TOKEN=BLAHBLAHMYTOKEN \
  -e 'INTERVAL=30s' \
  -e 'PIHolePort=8800' \
  -e 'PORT=9617' \
  -p 9617:9617 \
  ekofr/pihole-exporter:latest

running ubuntu server 20.04 lts, docker 20.10.2
I am trying to self host both pihole and the exporter from the same docker.
I maybe totally a noob, but I think something is wrong.
But any help would be awesome, thanks.
Log:
But no matter which options I am putting in, as well as exposing the PIHolePort
2021/01/15 17:08:05 ------------------------------------
2021/01/15 17:08:05 -  PI-Hole exporter configuration  -
2021/01/15 17:08:05 ------------------------------------
2021/01/15 17:08:05 PIHoleProtocol : http
2021/01/15 17:08:05 PIHoleHostname : 192.168.1.200
2021/01/15 17:08:05 PIHolePort : 80
2021/01/15 17:08:05 Pi-Hole Authentication Method : PIHoleApiToken
2021/01/15 17:08:05 Port : 9617
2021/01/15 17:08:05 Interval : 30s
2021/01/15 17:08:05 ------------------------------------

**Comment by raghuram-periaswamy** [comment]
@DasCondor The name of `env` variable is incorrect. It should be `PIHOLE_PORT=8800`.

**Comment by DasCondor** [comment]
Works for me, thanks.
