### ISSUE TITLE
I can't change port 

### ISSUE THREAD

**Issue by miniwilliams** [eko/pihole-exporter#70]
I'm having trouble get the docker container talking to my pi-hole container 

When its running I get this error 

2021/01/27 21:44:25 Unable to unmarshal PI-Hole statistics to statistics struct model invalid character '<' looking for beginning of value | stderr

I think the problem is its trying to access my pi-hole management on port 80 but I'm using 8888 

How can you change that please

**Comment by vgeorgiev69** [comment]
You can use PIHOLE_HOSTNAME=x.x.x.x:portnumber, mine is 88 and it's working fine. The ports should be: "9617:9617"

**Comment by tajchert** [comment]
Did you manged to get it working?
I declare pihole port as:
`-e 'PIHOLE_HOSTNAME=192.168.50.102:6060' \`

but pihole-exporter log is:

```Creating client with config <Config@C0000C40F0 PIHoleProtocol=http, PIHoleHostname=192.168.50.102:6060, PIHolePort=80, PIHolePassword=*****, BindAddr=, Port=0>\n```

and it doesn't work. Seems like it is still trying to use port 80.

**Comment by tajchert** [comment]
EDIT:
To change port using docker you can use `PIHOLE_PORT` parameter.

Seems to be working but my issue is somewhere else.
