### ISSUE TITLE
docker: from scratch image?

### ISSUE THREAD

**Issue by IvanDelsinne** [eko/pihole-exporter#8]
The current final image starts from alpine.

Wouldn't it work with a `FROM scratch`, thus greatly reducing the production image size?

**Comment by eko** [comment]
Hi @IvanDelsinne,

I just updated the Dockerfile and now building from scratch which decrease the image size from 17MB to 9.6MB.

Thank you

**Comment by eko** [comment]
I also added `upx` compression so the latest image is now 2.39MB size!

**Comment by IvanDelsinne** [comment]
Nice work
